apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: healthcare-hlf
  name: rca-aggregator
spec:
  selector:
    matchLabels:
      app: rca-aggregator
  replicas: 1
  template:
    metadata:
      labels:
        app: rca-aggregator
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hlf-pvc
      containers:

        - name: rca-aggregator
          image: hyperledger/fabric-ca:latest
          imagePullPolicy: "IfNotPresent"
          env:
           - name: FABRIC_CA_SERVER_CA_NAME
             value: rca-aggregator
           - name: FABRIC_CA_SERVER_TLS_ENABLED
             value: "true"
          command:
            [
              "fabric-ca-server" ,
              "start", "-b" ,"rca-aggregator-admin:rca-aggregator-adminpw","--port","10054", "-d"
            ] 
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "50m"
          volumeMounts:
            - name: data
              mountPath: /etc/hyperledger/fabric-ca-server
              subPath: organizations/fabric-ca/aggregatorRCA
---

apiVersion: v1
kind: Service
metadata:
  namespace: healthcare-hlf
  name: rca-aggregator
  
  labels:
    app: rca-aggregator
spec:
  type: NodePort
  selector:
    app: rca-aggregator
  ports:
    - protocol: TCP
      targetPort: 10054
      port: 10054
      nodePort: 30100