apiVersion: v1
kind: PersistentVolume
metadata:
  name: hlf-pv
spec:
  storageClassName: standard #efs-sc3
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-0d7b6ad3edd0882a2.efs.us-east-1.amazonaws.com
    path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: healthcare-hlf
  name: hlf-pvc
spec:
  storageClassName: standard #efs-sc3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4050Mi
   
