apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: healthcare-hlf
  name: cli-peer%NUM%-%ORG%
spec:
  selector:
    matchLabels:
      name: cli-peer%NUM%-%ORG%
  template:
    metadata:
      labels:
        name: cli-peer%NUM%-%ORG%
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: hlf-pvc

      containers:
        - name: cli-peer%NUM%-%ORG%
          stdin: true
          tty: true
          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "90m"
          image: hyperledger/fabric-tools:2.3
          workingDir: /
          env:
            - name: ORDERER_CA
              value: /organizations/ordererOrganizations/%ORDERER_DOMAIN%/tlsca.%ORDERER_DOMAIN%-cert.pem

            - name: CORE_PEER_ADDRESS
              value: peer%NUM%-%ORG%:7051
            - name: CORE_PEER_ID
              value: cli-peer%NUM%-%ORG%.%DOMAIN%
            - name: CORE_PEER_LOCALMSPID
              value: %ORG%MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /organizations/peerOrganizations/%ORG%.%DOMAIN%/users/%ADMIN_NAME%@%ORG%.%DOMAIN%/msp
            - name: CORE_PEER_TLS_CERT_FILE
              value: /organizations/peerOrganizations/%ORG%.%DOMAIN%/peers/peer%NUM%-%ORG%.%DOMAIN%/tls/server.crt
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_KEY_FILE
              value: /organizations/peerOrganizations/%ORG%.%DOMAIN%/peers/peer%NUM%-%ORG%.%DOMAIN%/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /organizations/peerOrganizations/%ORG%.%DOMAIN%/peers/peer%NUM%-%ORG%.%DOMAIN%/tls/ca.crt
            - name: FABRIC_LOGGING_SPEC
              value: ERROR
            - name: GOPATH
              value: /opt/gopath
            - name: SYS_CHANNEL
              value: system-channel
            - name: CORE_CHAINCODE_BUILDER
              value: hyperledger/fabric-ccenv:1.4.8
            - name: FABRIC_LOGGING_SPEC
              value: DEBUG
          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /configtx
              name: fabricfiles
              subPath: configtx
            - mountPath: /channel-artifacts
              name: fabricfiles
              subPath: channel-artifacts
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
            - mountPath: /opt/gopath/src/github.com/chaincode
              name: fabricfiles
              subPath: chaincode
